// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'C:/Users/lin/monorepo/nx-pnpm/node_modules/.pnpm/dumi@2.3.6_@babel+core@7.24.6_@swc+helpers@0.5.1_@types+node@20.5.1_@types+react@18.3.3_eslin_ssnesxiulmvmzswaybqwvxuuoy/node_modules/dumi/theme-default/slots/SourceCodeEditor/index.js';
