// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import nprogress from 'C:/Users/lin/monorepo/nx-pnpm/node_modules/.pnpm/nprogress@0.2.0/node_modules/nprogress';
import './nprogress.css';
import UserLoading from 'C:/Users/lin/monorepo/nx-pnpm/node_modules/.pnpm/dumi@2.3.6_@babel+core@7.24.6_@swc+helpers@0.5.1_@types+node@20.5.1_@types+react@18.3.3_eslin_ssnesxiulmvmzswaybqwvxuuoy/node_modules/dumi/dist/client/pages/Loading';
import React, { useLayoutEffect, type FC } from 'react';
import { useSiteData } from 'dumi';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    }
  }, []);

  return <UserLoading />
}

export default DumiLoading;
